/*
 * Panel_CifrasEnLetras.java
 *
 * Created on 15 de diciembre de 2007, 19:55
 */

package net.proinf.test.gramatica;

import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import net.proinf.gramatica.*;

/**
 *
 * @author  Administrador
 */
public class GramaticaPanel extends javax.swing.JPanel implements Observer {
    
    private GramaticaModelo modelo = null;
    private DefaultListModel listmodelPalabras = new DefaultListModel();
    
    public GramaticaPanel(GramaticaModelo modelo) {
        this();         
        this.modelo = modelo;
        modelo.addObserver(this);
        
        
        for (Palabra palabra: new Palabras("camión categoría fábula cliente águila")) 
            listmodelPalabras.addElement(palabra);
    }
        
    /** Creates new form Panel_CifrasEnLetras */
    public GramaticaPanel() {
        initComponents();           
        //textfieldPalabra.requestFocus();
    }   
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPrincipal = new javax.swing.JTabbedPane();
        panelEntrada = new javax.swing.JPanel();
        labelTexto = new javax.swing.JLabel();
        scrollTexto = new javax.swing.JScrollPane();
        textareaTexto = new javax.swing.JTextArea();
        buttonEvaluar = new javax.swing.JButton();
        buttonPalabraOmision = new javax.swing.JButton();
        labelAutor = new javax.swing.JLabel();
        panelEvaluacion = new javax.swing.JPanel();
        splitPalabras = new javax.swing.JSplitPane();
        panelPalabras = new javax.swing.JPanel();
        labelPalabras = new javax.swing.JLabel();
        textfieldPalabra = new javax.swing.JTextField();
        scrollPalabras = new javax.swing.JScrollPane();
        listPalabras = new javax.swing.JList();
        buttonIntroducirPalabra = new javax.swing.JButton();
        buttonBorrarPalabra = new javax.swing.JButton();
        tabbedPalabra = new javax.swing.JTabbedPane();
        panelAnalisis = new javax.swing.JPanel();
        labelSilabas = new javax.swing.JLabel();
        labelAcentuacion = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        textfieldSilabas = new javax.swing.JTextField();
        comboAcentuacion = new javax.swing.JComboBox();
        comboGenero = new javax.swing.JComboBox();
        comboNumero = new javax.swing.JComboBox();
        buttonCambiar = new javax.swing.JButton();
        panelVariaciones = new javax.swing.JPanel();
        labelPlural = new javax.swing.JLabel();
        textfieldPlural = new javax.swing.JTextField();
        labelCuantificar = new javax.swing.JLabel();
        textfieldCuantificar = new javax.swing.JTextField();
        spinnerCuantificar = new javax.swing.JSpinner();
        labelCapitalizar = new javax.swing.JLabel();
        textfieldCapitalizar = new javax.swing.JTextField();
        labelArticulo = new javax.swing.JLabel();
        textfieldArticuloIndeterminadoSingular = new javax.swing.JTextField();
        textfieldArticuloIndeterminadoPlural = new javax.swing.JTextField();
        textfieldArticuloDeterminadoSingular = new javax.swing.JTextField();
        textfieldArticuloDeterminadoPlural = new javax.swing.JTextField();
        labelPreposicion = new javax.swing.JLabel();
        textfieldAnteponerDe = new javax.swing.JTextField();
        textfieldAnteponerA = new javax.swing.JTextField();
        panelEnumeracion = new javax.swing.JPanel();
        textfieldConcepto = new javax.swing.JTextField();
        checkboxConcepto = new javax.swing.JCheckBox();
        scrollTexto1 = new javax.swing.JScrollPane();
        textareaEnumeracion = new javax.swing.JTextArea();

        tabbedPrincipal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPrincipalStateChanged(evt);
            }
        });

        panelEntrada.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

        labelTexto.setLabelFor(textareaTexto);
        labelTexto.setText("Texto:");

        textareaTexto.setColumns(20);
        textareaTexto.setLineWrap(true);
        textareaTexto.setRows(5);
        textareaTexto.setWrapStyleWord(true);
        textareaTexto.setFocusCycleRoot(true);
        textareaTexto.setMargin(new java.awt.Insets(4, 4, 4, 4));
        scrollTexto.setViewportView(textareaTexto);

        buttonEvaluar.setFont(new java.awt.Font("Tahoma", 1, 11));
        buttonEvaluar.setText("Evaluar...");
        buttonEvaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEvaluarActionPerformed(evt);
            }
        });

        buttonPalabraOmision.setText("Por omisión");
        buttonPalabraOmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPalabraOmisionActionPerformed(evt);
            }
        });

        labelAutor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAutor.setText("v0.08 © 2008 ProInf.net");

        org.jdesktop.layout.GroupLayout panelEntradaLayout = new org.jdesktop.layout.GroupLayout(panelEntrada);
        panelEntrada.setLayout(panelEntradaLayout);
        panelEntradaLayout.setHorizontalGroup(
            panelEntradaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelEntradaLayout.createSequentialGroup()
                .add(panelEntradaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelTexto)
                    .add(buttonEvaluar))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 273, Short.MAX_VALUE)
                .add(panelEntradaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(buttonPalabraOmision)
                    .add(labelAutor)))
            .add(scrollTexto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        panelEntradaLayout.setVerticalGroup(
            panelEntradaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelEntradaLayout.createSequentialGroup()
                .add(panelEntradaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonPalabraOmision)
                    .add(labelTexto))
                .add(1, 1, 1)
                .add(scrollTexto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelEntradaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonEvaluar)
                    .add(labelAutor)))
        );

        tabbedPrincipal.addTab("Entrada", panelEntrada);

        splitPalabras.setBorder(null);
        splitPalabras.setContinuousLayout(true);

        panelPalabras.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 4));

        labelPalabras.setLabelFor(textfieldPalabra);
        labelPalabras.setText("Palabra:");

        textfieldPalabra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textfieldPalabraKeyPressed(evt);
            }
        });

        listPalabras.setModel(listmodelPalabras);
        listPalabras.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPalabrasValueChanged(evt);
            }
        });
        scrollPalabras.setViewportView(listPalabras);

        buttonIntroducirPalabra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/proinf/test/gramatica/add.png"))); // NOI18N
        buttonIntroducirPalabra.setText("Introducir");
        buttonIntroducirPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIntroducirPalabraActionPerformed(evt);
            }
        });

        buttonBorrarPalabra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/proinf/test/gramatica/delete.png"))); // NOI18N
        buttonBorrarPalabra.setText("Borrar");
        buttonBorrarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarPalabraActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panelPalabrasLayout = new org.jdesktop.layout.GroupLayout(panelPalabras);
        panelPalabras.setLayout(panelPalabrasLayout);
        panelPalabrasLayout.setHorizontalGroup(
            panelPalabrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelPalabrasLayout.createSequentialGroup()
                .add(labelPalabras)
                .addContainerGap(61, Short.MAX_VALUE))
            .add(textfieldPalabra, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
            .add(buttonBorrarPalabra, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
            .add(scrollPalabras, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
            .add(buttonIntroducirPalabra, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPalabrasLayout.setVerticalGroup(
            panelPalabrasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelPalabrasLayout.createSequentialGroup()
                .add(labelPalabras)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textfieldPalabra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonIntroducirPalabra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrollPalabras, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonBorrarPalabra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        splitPalabras.setLeftComponent(panelPalabras);

        tabbedPalabra.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 0));

        panelAnalisis.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));

        labelSilabas.setLabelFor(textfieldSilabas);
        labelSilabas.setText("Sílabas:");

        labelAcentuacion.setLabelFor(comboAcentuacion);
        labelAcentuacion.setText("Acentuación:");

        labelGenero.setLabelFor(comboGenero);
        labelGenero.setText("Género: *");

        labelNumero.setLabelFor(comboNumero);
        labelNumero.setText("Número: *");

        textfieldSilabas.setEditable(false);

        comboAcentuacion.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        comboAcentuacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "aguda", "llana", "esdrújula", "sobreesdrújula" }));
        comboAcentuacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboAcentuacionItemStateChanged(evt);
            }
        });

        comboGenero.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        comboGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "neutro", "masculino", "femenino" }));
        comboGenero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboGeneroItemStateChanged(evt);
            }
        });

        comboNumero.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        comboNumero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "singular", "plural" }));
        comboNumero.setOpaque(false);
        comboNumero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboNumeroItemStateChanged(evt);
            }
        });

        buttonCambiar.setText("Cambiar*");
        buttonCambiar.setEnabled(false);
        buttonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCambiarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panelAnalisisLayout = new org.jdesktop.layout.GroupLayout(panelAnalisis);
        panelAnalisis.setLayout(panelAnalisisLayout);
        panelAnalisisLayout.setHorizontalGroup(
            panelAnalisisLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelAnalisisLayout.createSequentialGroup()
                .add(panelAnalisisLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelGenero)
                    .add(labelNumero)
                    .add(labelAcentuacion)
                    .add(labelSilabas))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelAnalisisLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(comboNumero, 0, 269, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, textfieldSilabas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .add(comboGenero, 0, 269, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, comboAcentuacion, 0, 269, Short.MAX_VALUE)))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelAnalisisLayout.createSequentialGroup()
                .addContainerGap()
                .add(buttonCambiar))
        );
        panelAnalisisLayout.setVerticalGroup(
            panelAnalisisLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelAnalisisLayout.createSequentialGroup()
                .add(panelAnalisisLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelSilabas)
                    .add(textfieldSilabas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelAnalisisLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelAcentuacion)
                    .add(comboAcentuacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelAnalisisLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelGenero)
                    .add(comboGenero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7)
                .add(panelAnalisisLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelNumero)
                    .add(comboNumero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(buttonCambiar)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        tabbedPalabra.addTab("Análisis", panelAnalisis);

        labelPlural.setLabelFor(textfieldCuantificar);
        labelPlural.setText("Plural:");

        textfieldPlural.setEditable(false);

        labelCuantificar.setLabelFor(spinnerCuantificar);
        labelCuantificar.setText("Cuantificar:");

        textfieldCuantificar.setEditable(false);

        spinnerCuantificar.setModel(new javax.swing.SpinnerNumberModel());
        spinnerCuantificar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerCuantificarStateChanged(evt);
            }
        });

        labelCapitalizar.setLabelFor(textfieldCapitalizar);
        labelCapitalizar.setText("Capitalizar:");

        textfieldCapitalizar.setEditable(false);

        labelArticulo.setText("Artículo:");

        textfieldArticuloIndeterminadoSingular.setEditable(false);

        textfieldArticuloIndeterminadoPlural.setEditable(false);

        textfieldArticuloDeterminadoSingular.setEditable(false);

        textfieldArticuloDeterminadoPlural.setEditable(false);

        labelPreposicion.setText("Preposición:");

        textfieldAnteponerDe.setEditable(false);

        textfieldAnteponerA.setEditable(false);

        org.jdesktop.layout.GroupLayout panelVariacionesLayout = new org.jdesktop.layout.GroupLayout(panelVariaciones);
        panelVariaciones.setLayout(panelVariacionesLayout);
        panelVariacionesLayout.setHorizontalGroup(
            panelVariacionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelVariacionesLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelVariacionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelPlural)
                    .add(labelCuantificar)
                    .add(labelCapitalizar)
                    .add(labelArticulo)
                    .add(labelPreposicion))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelVariacionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(textfieldAnteponerA, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .add(textfieldAnteponerDe, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .add(textfieldArticuloDeterminadoPlural, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .add(textfieldArticuloDeterminadoSingular, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .add(textfieldArticuloIndeterminadoPlural, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .add(textfieldArticuloIndeterminadoSingular, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .add(textfieldCapitalizar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .add(panelVariacionesLayout.createSequentialGroup()
                        .add(spinnerCuantificar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(textfieldCuantificar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                    .add(textfieldPlural, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelVariacionesLayout.setVerticalGroup(
            panelVariacionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelVariacionesLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelVariacionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelPlural)
                    .add(textfieldPlural, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelVariacionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelCuantificar)
                    .add(spinnerCuantificar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(textfieldCuantificar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelVariacionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelCapitalizar)
                    .add(textfieldCapitalizar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelVariacionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelArticulo)
                    .add(textfieldArticuloIndeterminadoSingular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textfieldArticuloIndeterminadoPlural, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textfieldArticuloDeterminadoSingular, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textfieldArticuloDeterminadoPlural, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelVariacionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelPreposicion)
                    .add(textfieldAnteponerDe, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textfieldAnteponerA, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        tabbedPalabra.addTab("Variaciones", panelVariaciones);

        splitPalabras.setRightComponent(tabbedPalabra);

        org.jdesktop.layout.GroupLayout panelEvaluacionLayout = new org.jdesktop.layout.GroupLayout(panelEvaluacion);
        panelEvaluacion.setLayout(panelEvaluacionLayout);
        panelEvaluacionLayout.setHorizontalGroup(
            panelEvaluacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelEvaluacionLayout.createSequentialGroup()
                .addContainerGap()
                .add(splitPalabras, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEvaluacionLayout.setVerticalGroup(
            panelEvaluacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelEvaluacionLayout.createSequentialGroup()
                .addContainerGap()
                .add(splitPalabras, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPrincipal.addTab("Evaluación", panelEvaluacion);

        textfieldConcepto.setText("palabra");

        checkboxConcepto.setText("Concepto:");
        checkboxConcepto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxConceptoItemStateChanged(evt);
            }
        });

        textareaEnumeracion.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        textareaEnumeracion.setColumns(20);
        textareaEnumeracion.setEditable(false);
        textareaEnumeracion.setLineWrap(true);
        textareaEnumeracion.setRows(5);
        textareaEnumeracion.setWrapStyleWord(true);
        textareaEnumeracion.setFocusCycleRoot(true);
        textareaEnumeracion.setMargin(new java.awt.Insets(4, 4, 4, 4));
        scrollTexto1.setViewportView(textareaEnumeracion);

        org.jdesktop.layout.GroupLayout panelEnumeracionLayout = new org.jdesktop.layout.GroupLayout(panelEnumeracion);
        panelEnumeracion.setLayout(panelEnumeracionLayout);
        panelEnumeracionLayout.setHorizontalGroup(
            panelEnumeracionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelEnumeracionLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelEnumeracionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, scrollTexto1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .add(panelEnumeracionLayout.createSequentialGroup()
                        .add(checkboxConcepto)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(textfieldConcepto, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEnumeracionLayout.setVerticalGroup(
            panelEnumeracionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelEnumeracionLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelEnumeracionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(checkboxConcepto)
                    .add(textfieldConcepto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(scrollTexto1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPrincipal.addTab("Enumeración", panelEnumeracion);

        tabbedPrincipal.setSelectedIndex(1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(tabbedPrincipal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(tabbedPrincipal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEvaluarActionPerformed
        Palabras palabras = new Palabras(textareaTexto.getText());
        tabbedPrincipal.setSelectedComponent(panelEvaluacion);
        
        listmodelPalabras.removeAllElements();
        for (Palabra palabra: palabras) listmodelPalabras.addElement(palabra);
        listPalabras.setSelectedIndex(0);
}//GEN-LAST:event_buttonEvaluarActionPerformed

    private void buttonPalabraOmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPalabraOmisionActionPerformed
        textareaTexto.setText(GramaticaTest.palabras());
    }//GEN-LAST:event_buttonPalabraOmisionActionPerformed

    private void buttonIntroducirPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIntroducirPalabraActionPerformed
        Palabra palabra = new Palabra(textfieldPalabra.getText());
        modelo.setPalabra(palabra);
    }//GEN-LAST:event_buttonIntroducirPalabraActionPerformed

    private void buttonBorrarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarPalabraActionPerformed
        Palabra palabra = (Palabra)listPalabras.getSelectedValue();
        if (palabra != null) { 
            listmodelPalabras.removeElement(palabra);
            textfieldPalabra.setText(palabra.toString());
            textfieldPalabra.requestFocus();
        }         
    }//GEN-LAST:event_buttonBorrarPalabraActionPerformed

    private void listPalabrasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPalabrasValueChanged
        Palabra palabra = (Palabra)listPalabras.getSelectedValue();
        modelo.setPalabra(palabra);        
    }//GEN-LAST:event_listPalabrasValueChanged

    private void tabbedPrincipalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPrincipalStateChanged
        if (tabbedPrincipal.getSelectedComponent() == panelEnumeracion) {        
            Object[] palabras = new Palabra[listmodelPalabras.getSize()];
            listmodelPalabras.copyInto(palabras);
            modelo.setPalabras(new Palabras(palabras));  
        }        
    }//GEN-LAST:event_tabbedPrincipalStateChanged

    private void spinnerCuantificarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerCuantificarStateChanged
        int elementos = ((Integer)spinnerCuantificar.getValue()).intValue();
        modelo.setNumeroElementos(elementos);
    }//GEN-LAST:event_spinnerCuantificarStateChanged

    private void checkboxConceptoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxConceptoItemStateChanged
        modelo.setConcepto(new Palabra(textfieldConcepto.getText()));
    }//GEN-LAST:event_checkboxConceptoItemStateChanged

    private void textfieldPalabraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldPalabraKeyPressed
        int key = evt.getKeyCode();
        if (key == java.awt.event.KeyEvent.VK_ENTER) {
            Palabra palabra = new Palabra(textfieldPalabra.getText());
            modelo.setPalabra(palabra);
        }
    }//GEN-LAST:event_textfieldPalabraKeyPressed

    private void comboAcentuacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboAcentuacionItemStateChanged
        buttonCambiar.setEnabled(true);
    }//GEN-LAST:event_comboAcentuacionItemStateChanged

    private void comboGeneroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboGeneroItemStateChanged
        buttonCambiar.setEnabled(true);
    }//GEN-LAST:event_comboGeneroItemStateChanged

    private void comboNumeroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboNumeroItemStateChanged
        buttonCambiar.setEnabled(true);
    }//GEN-LAST:event_comboNumeroItemStateChanged

    private void buttonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCambiarActionPerformed
        Palabra palabra = modelo.getPalabra();
        int indice = 0;
        
        /*indice = comboAcentuacion.getSelectedIndex();
        if (indice > 0) palabra.cambiarAcentuacion(Acentuacion.values()[indice-1]);*/
        
        indice = comboGenero.getSelectedIndex();
        if (indice > 0) palabra.cambiarGenero(Genero.values()[indice-1]);
        
        indice = comboNumero.getSelectedIndex();
        if (indice > 0) palabra.cambiarNumero(Numero.values()[indice-1]);
        
        modelo.setPalabra(palabra);
    }//GEN-LAST:event_buttonCambiarActionPerformed

    public void update(Observable o, Object arg) {
        if (tabbedPrincipal.getSelectedComponent() == panelEvaluacion) {
            Palabra palabra = modelo.getPalabra();            
            if (palabra == null || palabra.estaVacia()) return;            
                       
            boolean palabraEstaEnLista = listmodelPalabras.contains(palabra);            
            if (palabraEstaEnLista) {
                textfieldPalabra.setText(palabra.toString());                
                listPalabras.setSelectedValue(palabra, true);
            }
            else {                
                textfieldPalabra.requestFocus();
                listmodelPalabras.addElement(palabra);                
                listPalabras.setSelectedValue(palabra, true);
            }
            textfieldPalabra.setText("");
                       
            Palabra palabraPlural = palabra.enPlural();            
            int numeroElementos = modelo.getNumeroElementos();   
            
            spinnerCuantificar.setValue(new Integer(numeroElementos));
        
            // Análisis
            textfieldSilabas.setText(palabra.silabas().toString());
            comboAcentuacion.setSelectedItem(palabra.acentuacion().toString());
            comboGenero.setSelectedItem(palabra.genero().toString());
            comboNumero.setSelectedItem(palabra.numero().toString());
            buttonCambiar.setEnabled(false);

            // Variaciones
            textfieldPlural.setText(palabraPlural.toString());
            textfieldCapitalizar.setText(palabra.enCapital().toString());
            Articulo articulo = Articulo.determinado;
            textfieldAnteponerDe.setText(palabra.anteponerDe(articulo));
            textfieldAnteponerA.setText(palabra.anteponerA(articulo));
            textfieldCuantificar.setText(palabra.cuantificar(numeroElementos));                                  
            articulo = Articulo.indeterminado;           
            textfieldArticuloIndeterminadoSingular.setText(articulo.agregarPalabra(palabra));
            textfieldArticuloIndeterminadoPlural.setText(articulo.agregarPalabra(palabraPlural));
            articulo = Articulo.determinado;
            textfieldArticuloDeterminadoSingular.setText(articulo.agregarPalabra(palabra));
            textfieldArticuloDeterminadoPlural.setText(articulo.agregarPalabra(palabraPlural));            
        }
        else if (tabbedPrincipal.getSelectedComponent() == panelEnumeracion) {
            Palabras palabras = modelo.getPalabras();
            Palabra concepto = modelo.getConcepto();
            
            textfieldConcepto.setText(concepto.toString());
            if (checkboxConcepto.isSelected()) 
                textareaEnumeracion.setText(palabras.enumerarConcepto(concepto));
            else textareaEnumeracion.setText(palabras.enumerar(Articulo.determinado));            
        }    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBorrarPalabra;
    private javax.swing.JButton buttonCambiar;
    private javax.swing.JButton buttonEvaluar;
    private javax.swing.JButton buttonIntroducirPalabra;
    private javax.swing.JButton buttonPalabraOmision;
    private javax.swing.JCheckBox checkboxConcepto;
    private javax.swing.JComboBox comboAcentuacion;
    private javax.swing.JComboBox comboGenero;
    private javax.swing.JComboBox comboNumero;
    private javax.swing.JLabel labelAcentuacion;
    private javax.swing.JLabel labelArticulo;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelCapitalizar;
    private javax.swing.JLabel labelCuantificar;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelPalabras;
    private javax.swing.JLabel labelPlural;
    private javax.swing.JLabel labelPreposicion;
    private javax.swing.JLabel labelSilabas;
    private javax.swing.JLabel labelTexto;
    private javax.swing.JList listPalabras;
    private javax.swing.JPanel panelAnalisis;
    private javax.swing.JPanel panelEntrada;
    private javax.swing.JPanel panelEnumeracion;
    private javax.swing.JPanel panelEvaluacion;
    private javax.swing.JPanel panelPalabras;
    private javax.swing.JPanel panelVariaciones;
    private javax.swing.JScrollPane scrollPalabras;
    private javax.swing.JScrollPane scrollTexto;
    private javax.swing.JScrollPane scrollTexto1;
    private javax.swing.JSpinner spinnerCuantificar;
    private javax.swing.JSplitPane splitPalabras;
    private javax.swing.JTabbedPane tabbedPalabra;
    private javax.swing.JTabbedPane tabbedPrincipal;
    private javax.swing.JTextArea textareaEnumeracion;
    private javax.swing.JTextArea textareaTexto;
    private javax.swing.JTextField textfieldAnteponerA;
    private javax.swing.JTextField textfieldAnteponerDe;
    private javax.swing.JTextField textfieldArticuloDeterminadoPlural;
    private javax.swing.JTextField textfieldArticuloDeterminadoSingular;
    private javax.swing.JTextField textfieldArticuloIndeterminadoPlural;
    private javax.swing.JTextField textfieldArticuloIndeterminadoSingular;
    private javax.swing.JTextField textfieldCapitalizar;
    private javax.swing.JTextField textfieldConcepto;
    private javax.swing.JTextField textfieldCuantificar;
    private javax.swing.JTextField textfieldPalabra;
    private javax.swing.JTextField textfieldPlural;
    private javax.swing.JTextField textfieldSilabas;
    // End of variables declaration//GEN-END:variables
    
}
